---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-vault-pipeline
  namespace: monitoring
  labels:
    app: logstash-vault
data:
  logstash.conf: |
    input {
      tcp {
        port => 9091
        codec => json
      }
    }
    output { 
      elasticsearch { 
        hosts => ["http://es-master.monitoring:9200"]
        index => "logstash-vault-%{+YYYY.MM.dd}" 
      } 
    }
