apiVersion: v1
kind: Service
metadata:
  name: logstash-vault
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: logstash-vault
