kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: kind-node:test4
  extraMounts:
  - hostPath: /opt/kind-data
    containerPath: /opt/kind-data
- role: worker
  image: kind-node:test4
  extraMounts:
  - hostPath: /opt/kind-data
    containerPath: /opt/kind-data
- role: worker
  image: kind-node:test4
  extraMounts:
  - hostPath: /opt/kind-data
    containerPath: /opt/kind-data
- role: worker
  image: kind-node:test4
  extraMounts:
  - hostPath: /opt/kind-data
    containerPath: /opt/kind-data
