apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-prometheus
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: prometheus
  storageClassName: standard
  volumeMode: Filesystem
