apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless
  namespace: prometheus
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
