---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-a
  labels:
    app: prometheus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/prometheus-a
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-b
  labels:
    app: prometheus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/prometheus-b
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-c
  labels:
    app: prometheus
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/prometheus-c
    type: Directory
