---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-master-a
  labels:
    app: es-master
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/es-master-a
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-master-b
  labels:
    app: es-master
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/es-master-b
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-master-c
  labels:
    app: es-master
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/es-master-c
    type: Directory
