apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-hq
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-hq
  template:
    metadata:
      labels:
        app: es-hq
    spec:
      containers:
      - image: elastichq/elasticsearch-hq:release-v3.5.12
        name: es-hq
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 5
