apiVersion: v1
kind: Service
metadata:
  name: es-hq
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: es-hq
