apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: cadvisor
  type: ClusterIP
