---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-data-a
  labels:
    app: es-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/es-data-a
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-data-b
  labels:
    app: es-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /opt/kind-data/es-data-b
    type: Directory
