apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
  namespace: vault
data:
  extraconfig-from-values.hcl: |-
    ui = true
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
    }
    storage "consul" {
      path = "vault"
      address = "consul.consul:8500"
    }
    service_registration "kubernetes" {}
