apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault
  labels:
    app: vault
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
