spec:
  template:
    spec:
      initContainers:
        - name: init-chown-data
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              subPathExpr: $(POD_NAME)
      containers:
        - name: grafana
          volumeMounts:
            - mountPath: "/var/lib/grafana"
              subPathExpr: $(POD_NAME)
